import {
  Apple,
  Award,
  Baby,
  Banknote,
  Beer,
  Bike,
  Book,
  BookOpen,
  Bookmark,
  Briefcase,
  Building,
  Bus,
  Calculator,
  Camera,
  Car,
  CarTaxiFront,
  Cat,
  CircleDollarSign,
  Cloud,
  Coffee,
  Coins,
  CreditCard,
  Croissant,
  Dog,
  Drill,
  Droplet,
  Dumbbell,
  FileText,
  Film,
  Flame,
  Flower,
  Footprints,
  Fuel,
  Gamepad2,
  Gift,
  Glasses,
  GraduationCap,
  HandCoins,
  Hammer,
  HeartPulse,
  Headphones,
  Home,
  Key,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Monitor,
  Moon,
  MoreHorizontal,
  Mountain,
  Music,
  Package,
  Palette,
  ParkingSquare,
  PawPrint,
  Pencil,
  Percent,
  PiggyBank,
  Pill,
  Plane,
  PlusCircle,
  Receipt,
  RotateCcw,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Snowflake,
  Star,
  Stethoscope,
  Sun,
  Target,
  Ticket,
  Train,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  User,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Watch,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICON_REGISTRY: Record<string, LucideIcon> = {
  // money / finance
  banknote: Banknote,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  "credit-card": CreditCard,
  coins: Coins,
  "hand-coins": HandCoins,
  "circle-dollar-sign": CircleDollarSign,
  landmark: Landmark,
  receipt: Receipt,
  calculator: Calculator,
  percent: Percent,
  // work / income
  briefcase: Briefcase,
  "trending-up": TrendingUp,
  "rotate-ccw": RotateCcw,
  gift: Gift,
  "plus-circle": PlusCircle,
  // home / utilities
  home: Home,
  key: Key,
  building: Building,
  zap: Zap,
  droplet: Droplet,
  wifi: Wifi,
  flame: Flame,
  "file-text": FileText,
  // food
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  "shopping-cart": ShoppingCart,
  apple: Apple,
  croissant: Croissant,
  coffee: Coffee,
  beer: Beer,
  // transport
  car: Car,
  fuel: Fuel,
  "car-taxi-front": CarTaxiFront,
  bus: Bus,
  bike: Bike,
  "parking-square": ParkingSquare,
  truck: Truck,
  train: Train,
  plane: Plane,
  // health
  "heart-pulse": HeartPulse,
  shield: Shield,
  pill: Pill,
  stethoscope: Stethoscope,
  dumbbell: Dumbbell,
  // leisure / entertainment
  smile: Smile,
  ticket: Ticket,
  tv: Tv,
  film: Film,
  music: Music,
  headphones: Headphones,
  "gamepad-2": Gamepad2,
  camera: Camera,
  // education
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  book: Book,
  pencil: Pencil,
  // shopping / personal
  "shopping-bag": ShoppingBag,
  shirt: Shirt,
  laptop: Laptop,
  monitor: Monitor,
  smartphone: Smartphone,
  watch: Watch,
  glasses: Glasses,
  lamp: Lamp,
  package: Package,
  scissors: Scissors,
  user: User,
  baby: Baby,
  // pets
  dog: Dog,
  cat: Cat,
  "paw-print": PawPrint,
  // tools
  wrench: Wrench,
  hammer: Hammer,
  drill: Drill,
  palette: Palette,
  // nature / weather
  leaf: Leaf,
  flower: Flower,
  "tree-pine": TreePine,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  snowflake: Snowflake,
  umbrella: Umbrella,
  mountain: Mountain,
  // generic
  star: Star,
  bookmark: Bookmark,
  trophy: Trophy,
  award: Award,
  target: Target,
  footprints: Footprints,
  "more-horizontal": MoreHorizontal,
};

export type IconName = keyof typeof ICON_REGISTRY;

export const ICON_NAMES = Object.keys(ICON_REGISTRY) as IconName[];

export function getIconComponent(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return ICON_REGISTRY[name] ?? null;
}
